import { createContext, useContext, useState } from "react";

const LanguageContext = createContext();

const translations = {
  en: {
    dashboard: "Dashboard",
    products: "Products",
    categories: "Categories",
    orders: "Orders",
    customers: "Customers",
    users: "Users",
    settings: "Settings",
    logout: "Logout",
    profile: "Profile",
    add: "Add",
    edit: "Edit",
    delete: "Delete",
    save: "Save",
    cancel: "Cancel",
    search: "Search",
    filter: "Filter",
    apply: "Apply",
    close: "Close",
    loading: "Loading",
    error: "Error",
    success: "Success",
    addProduct: "Add Product",
    manageProductCatalog: "Manage your product catalog",
    searchProducts: "Search products...",
    productName: "Product Name",
    category: "Category",
    price: "Price",
    status: "Status",
    actions: "Actions",
    noProductsFound: "No products found",
    tableView: "Table View",
    gridView: "Grid View",
    sections: "Sections",
    notifications: "Notifications",
    noNewNotifications: "No new notifications",
    selectLanguage: "Select Language",
    poweredByGoogleTranslate: "Powered by Google Translate",
    profileSettings: "Profile Settings",
    changeLanguage: "Change Language",
    signOut: "Sign Out",
    image: "Image",
    brand: "Brand",
    noImage: "No Image",
    show: "Show",
    entries: "entries",
    prev: "Prev",
    next: "Next",
    login: "Login",
    emailOrPhone: "Email or Phone",
    enterEmailOrPhone: "Enter email or phone",
    password: "Password",
    enterPassword: "Enter password",
    signingIn: "Signing In...",
    signIn: "Sign In",
    invalidCredentials: "Invalid credentials",
  },
  es: {
    dashboard: "Panel de Control",
    products: "Productos",
    categories: "Categorías",
    orders: "Pedidos",
    customers: "Clientes",
    users: "Usuarios",
    settings: "Configuración",
    logout: "Cerrar Sesión",
    profile: "Perfil",
    add: "Agregar",
    edit: "Editar",
    delete: "Eliminar",
    save: "Guardar",
    cancel: "Cancelar",
    search: "Buscar",
    filter: "Filtrar",
    apply: "Aplicar",
    close: "Cerrar",
    loading: "Cargando",
    error: "Error",
    success: "Éxito",
    addProduct: "Agregar Producto",
    manageProductCatalog: "Administra tu catálogo de productos",
    searchProducts: "Buscar productos...",
    productName: "Nombre del Producto",
    category: "Categoría",
    price: "Precio",
    status: "Estado",
    actions: "Acciones",
    noProductsFound: "No se encontraron productos",
    tableView: "Vista de Tabla",
    gridView: "Vista de Cuadrícula",
    sections: "Secciones",
    notifications: "Notificaciones",
    noNewNotifications: "Sin notificaciones nuevas",
    selectLanguage: "Seleccionar Idioma",
    poweredByGoogleTranslate: "Impulsado por Google Translate",
    profileSettings: "Configuración de Perfil",
    changeLanguage: "Cambiar Idioma",
    signOut: "Cerrar Sesión",
    image: "Imagen",
    brand: "Marca",
    noImage: "Sin Imagen",
    show: "Mostrar",
    entries: "entradas",
    prev: "Anterior",
    next: "Siguiente",
    login: "Iniciar Sesión",
    emailOrPhone: "Correo o Teléfono",
    enterEmailOrPhone: "Ingresa correo o teléfono",
    password: "Contraseña",
    enterPassword: "Ingresa contraseña",
    signingIn: "Iniciando Sesión...",
    signIn: "Iniciar Sesión",
    invalidCredentials: "Credenciales inválidas",
  },
  fr: {
    dashboard: "Tableau de Bord",
    products: "Produits",
    categories: "Catégories",
    orders: "Commandes",
    customers: "Clients",
    users: "Utilisateurs",
    settings: "Paramètres",
    logout: "Déconnexion",
    profile: "Profil",
    add: "Ajouter",
    edit: "Modifier",
    delete: "Supprimer",
    save: "Enregistrer",
    cancel: "Annuler",
    search: "Rechercher",
    filter: "Filtrer",
    apply: "Appliquer",
    close: "Fermer",
    loading: "Chargement",
    error: "Erreur",
    success: "Succès",
    addProduct: "Ajouter un Produit",
    manageProductCatalog: "Gérez votre catalogue de produits",
    searchProducts: "Rechercher des produits...",
    productName: "Nom du Produit",
    category: "Catégorie",
    price: "Prix",
    status: "Statut",
    actions: "Actions",
    noProductsFound: "Aucun produit trouvé",
    tableView: "Vue Tableau",
    gridView: "Vue Grille",
    sections: "Sections",
    notifications: "Notifications",
    noNewNotifications: "Pas de nouvelles notifications",
    selectLanguage: "Sélectionner la Langue",
    poweredByGoogleTranslate: "Alimenté par Google Translate",
    profileSettings: "Paramètres de Profil",
    changeLanguage: "Changer de Langue",
    signOut: "Se Déconnecter",
    image: "Image",
    brand: "Marque",
    noImage: "Pas d'Image",
    show: "Afficher",
    entries: "entrées",
    prev: "Précédent",
    next: "Suivant",
    login: "Connexion",
    emailOrPhone: "Email ou Téléphone",
    enterEmailOrPhone: "Entrez email ou téléphone",
    password: "Mot de passe",
    enterPassword: "Entrez le mot de passe",
    signingIn: "Connexion en cours...",
    signIn: "Se Connecter",
    invalidCredentials: "Identifiants invalides",
  },
  de: {
    dashboard: "Armaturenbrett",
    products: "Produkte",
    categories: "Kategorien",
    orders: "Bestellungen",
    customers: "Kunden",
    users: "Benutzer",
    settings: "Einstellungen",
    logout: "Abmelden",
    profile: "Profil",
    add: "Hinzufügen",
    edit: "Bearbeiten",
    delete: "Löschen",
    save: "Speichern",
    cancel: "Abbrechen",
    search: "Suchen",
    filter: "Filtern",
    apply: "Anwenden",
    close: "Schließen",
    loading: "Wird geladen",
    error: "Fehler",
    success: "Erfolg",
    addProduct: "Produkt Hinzufügen",
    manageProductCatalog: "Verwalten Sie Ihren Produktkatalog",
    searchProducts: "Produkte suchen...",
    productName: "Produktname",
    category: "Kategorie",
    price: "Preis",
    status: "Status",
    actions: "Aktionen",
    noProductsFound: "Keine Produkte gefunden",
    tableView: "Tabellenansicht",
    gridView: "Rasteransicht",
    sections: "Abschnitte",
    notifications: "Benachrichtigungen",
    noNewNotifications: "Keine neuen Benachrichtigungen",
    selectLanguage: "Sprache Wählen",
    poweredByGoogleTranslate: "Unterstützt von Google Translate",
    profileSettings: "Profileinstellungen",
    changeLanguage: "Sprache Ändern",
    signOut: "Abmelden",
    image: "Bild",
    brand: "Marke",
    noImage: "Kein Bild",
    show: "Anzeigen",
    entries: "Einträge",
    prev: "Zurück",
    next: "Weiter",
    login: "Anmelden",
    emailOrPhone: "E-Mail oder Telefon",
    enterEmailOrPhone: "E-Mail oder Telefon eingeben",
    password: "Passwort",
    enterPassword: "Passwort eingeben",
    signingIn: "Wird angemeldet...",
    signIn: "Anmelden",
    invalidCredentials: "Ungültige Anmeldedaten",
  },
  it: {
    dashboard: "Cruscotto",
    products: "Prodotti",
    categories: "Categorie",
    orders: "Ordini",
    customers: "Clienti",
    users: "Utenti",
    settings: "Impostazioni",
    logout: "Esci",
    profile: "Profilo",
    add: "Aggiungi",
    edit: "Modifica",
    delete: "Elimina",
    save: "Salva",
    cancel: "Annulla",
    search: "Cerca",
    filter: "Filtra",
    apply: "Applica",
    close: "Chiudi",
    loading: "Caricamento",
    error: "Errore",
    success: "Successo",
    addProduct: "Aggiungi Prodotto",
    manageProductCatalog: "Gestisci il tuo catalogo prodotti",
    searchProducts: "Cerca prodotti...",
    productName: "Nome Prodotto",
    category: "Categoria",
    price: "Prezzo",
    status: "Stato",
    actions: "Azioni",
    noProductsFound: "Nessun prodotto trovato",
    tableView: "Vista Tabella",
    gridView: "Vista Griglia",
    sections: "Sezioni",
    notifications: "Notifiche",
    noNewNotifications: "Nessuna nuova notifica",
    selectLanguage: "Seleziona Lingua",
    poweredByGoogleTranslate: "Powered by Google Translate",
    profileSettings: "Impostazioni Profilo",
    changeLanguage: "Cambia Lingua",
    signOut: "Esci",
    image: "Immagine",
    brand: "Marca",
    noImage: "Nessuna Immagine",
    show: "Mostra",
    entries: "voci",
    prev: "Precedente",
    next: "Successivo",
    login: "Accedi",
    emailOrPhone: "Email o Telefono",
    enterEmailOrPhone: "Inserisci email o telefono",
    password: "Password",
    enterPassword: "Inserisci password",
    signingIn: "Accesso in corso...",
    signIn: "Accedi",
    invalidCredentials: "Credenziali non valide",
  },
  pt: {
    dashboard: "Painel de Controle",
    products: "Produtos",
    categories: "Categorias",
    orders: "Pedidos",
    customers: "Clientes",
    users: "Usuários",
    settings: "Configurações",
    logout: "Sair",
    profile: "Perfil",
    add: "Adicionar",
    edit: "Editar",
    delete: "Excluir",
    save: "Salvar",
    cancel: "Cancelar",
    search: "Pesquisar",
    filter: "Filtrar",
    apply: "Aplicar",
    close: "Fechar",
    loading: "Carregando",
    error: "Erro",
    success: "Sucesso",
    addProduct: "Adicionar Produto",
    manageProductCatalog: "Gerencie seu catálogo de produtos",
    searchProducts: "Pesquisar produtos...",
    productName: "Nome do Produto",
    category: "Categoria",
    price: "Preço",
    status: "Status",
    actions: "Ações",
    noProductsFound: "Nenhum produto encontrado",
    tableView: "Visualização em Tabela",
    gridView: "Visualização em Grade",
    sections: "Seções",
    notifications: "Notificações",
    noNewNotifications: "Sem novas notificações",
    selectLanguage: "Selecionar Idioma",
    poweredByGoogleTranslate: "Powered by Google Translate",
    profileSettings: "Configurações de Perfil",
    changeLanguage: "Mudar Idioma",
    signOut: "Sair",
    image: "Imagem",
    brand: "Marca",
    noImage: "Sem Imagem",
    show: "Mostrar",
    entries: "entradas",
    prev: "Anterior",
    next: "Próximo",
    login: "Entrar",
    emailOrPhone: "Email ou Telefone",
    enterEmailOrPhone: "Digite email ou telefone",
    password: "Senha",
    enterPassword: "Digite a senha",
    signingIn: "Entrando...",
    signIn: "Entrar",
    invalidCredentials: "Credenciais inválidas",
  },
  ru: {
    dashboard: "Панель управления",
    products: "Продукты",
    categories: "Категории",
    orders: "Заказы",
    customers: "Клиенты",
    users: "Пользователи",
    settings: "Настройки",
    logout: "Выход",
    profile: "Профиль",
    add: "Добавить",
    edit: "Редактировать",
    delete: "Удалить",
    save: "Сохранить",
    cancel: "Отмена",
    search: "Поиск",
    filter: "Фильтр",
    apply: "Применить",
    close: "Закрыть",
    loading: "Загрузка",
    error: "Ошибка",
    success: "Успех",
    addProduct: "Добавить Продукт",
    manageProductCatalog: "Управляйте каталогом продуктов",
    searchProducts: "Поиск продуктов...",
    productName: "Название Продукта",
    category: "Категория",
    price: "Цена",
    status: "Статус",
    actions: "Действия",
    noProductsFound: "Продукты не найдены",
    tableView: "Табличный вид",
    gridView: "Сеточный вид",
    sections: "Разделы",
    notifications: "Уведомления",
    noNewNotifications: "Нет новых уведомлений",
    selectLanguage: "Выберите Язык",
    poweredByGoogleTranslate: "Powered by Google Translate",
    profileSettings: "Настройки Профиля",
    changeLanguage: "Изменить Язык",
    signOut: "Выход",
    image: "Изображение",
    brand: "Бренд",
    noImage: "Нет Изображения",
    show: "Показать",
    entries: "записи",
    prev: "Назад",
    next: "Далее",
    login: "Вход",
    emailOrPhone: "Email или Телефон",
    enterEmailOrPhone: "Введите email или телефон",
    password: "Пароль",
    enterPassword: "Введите пароль",
    signingIn: "Вход в систему...",
    signIn: "Вход",
    invalidCredentials: "Неверные учетные данные",
  },
  ja: {
    dashboard: "ダッシュボード",
    products: "製品",
    categories: "カテゴリー",
    orders: "注文",
    customers: "顧客",
    users: "ユーザー",
    settings: "設定",
    logout: "ログアウト",
    profile: "プロフィール",
    add: "追加",
    edit: "編集",
    delete: "削除",
    save: "保存",
    cancel: "キャンセル",
    search: "検索",
    filter: "フィルター",
    apply: "適用",
    close: "閉じる",
    loading: "読み込み中",
    error: "エラー",
    success: "成功",
    addProduct: "製品を追加",
    manageProductCatalog: "製品カタログを管理",
    searchProducts: "製品を検索...",
    productName: "製品名",
    category: "カテゴリー",
    price: "価格",
    status: "ステータス",
    actions: "アクション",
    noProductsFound: "製品が見つかりません",
    tableView: "テーブルビュー",
    gridView: "グリッドビュー",
    sections: "セクション",
    notifications: "通知",
    noNewNotifications: "新しい通知はありません",
    selectLanguage: "言語を選択",
    poweredByGoogleTranslate: "Powered by Google Translate",
    profileSettings: "プロフィール設定",
    changeLanguage: "言語を変更",
    signOut: "サインアウト",
    image: "画像",
    brand: "ブランド",
    noImage: "画像なし",
    show: "表示",
    entries: "エントリ",
    prev: "前へ",
    next: "次へ",
    login: "ログイン",
    emailOrPhone: "メールまたは電話",
    enterEmailOrPhone: "メールまたは電話を入力",
    password: "パスワード",
    enterPassword: "パスワードを入力",
    signingIn: "ログイン中...",
    signIn: "ログイン",
    invalidCredentials: "無効な認証情報",
  },
  zh: {
    dashboard: "仪表板",
    products: "产品",
    categories: "类别",
    orders: "订单",
    customers: "客户",
    users: "用户",
    settings: "设置",
    logout: "登出",
    profile: "个人资料",
    add: "添加",
    edit: "编辑",
    delete: "删除",
    save: "保存",
    cancel: "取消",
    search: "搜索",
    filter: "筛选",
    apply: "应用",
    close: "关闭",
    loading: "加载中",
    error: "错误",
    success: "成功",
    addProduct: "添加产品",
    manageProductCatalog: "管理您的产品目录",
    searchProducts: "搜索产品...",
    productName: "产品名称",
    category: "类别",
    price: "价格",
    status: "状态",
    actions: "操作",
    noProductsFound: "未找到产品",
    tableView: "表格视图",
    gridView: "网格视图",
    sections: "部分",
    notifications: "通知",
    noNewNotifications: "没有新通知",
    selectLanguage: "选择语言",
    poweredByGoogleTranslate: "Powered by Google Translate",
    profileSettings: "个人资料设置",
    changeLanguage: "更改语言",
    signOut: "登出",
    image: "图像",
    brand: "品牌",
    noImage: "无图像",
    show: "显示",
    entries: "条目",
    prev: "上一页",
    next: "下一页",
    login: "登录",
    emailOrPhone: "邮箱或电话",
    enterEmailOrPhone: "输入邮箱或电话",
    password: "密码",
    enterPassword: "输入密码",
    signingIn: "正在登录...",
    signIn: "登录",
    invalidCredentials: "无效的凭证",
  },
  ar: {
    dashboard: "لوحة التحكم",
    products: "المنتجات",
    categories: "الفئات",
    orders: "الطلبات",
    customers: "العملاء",
    users: "المستخدمون",
    settings: "الإعدادات",
    logout: "تسجيل الخروج",
    profile: "الملف الشخصي",
    add: "إضافة",
    edit: "تحرير",
    delete: "حذف",
    save: "حفظ",
    cancel: "إلغاء",
    search: "بحث",
    filter: "تصفية",
    apply: "تطبيق",
    close: "إغلاق",
    loading: "جاري التحميل",
    error: "خطأ",
    success: "نجاح",
    addProduct: "إضافة منتج",
    manageProductCatalog: "إدارة كتالوج المنتجات الخاص بك",
    searchProducts: "البحث عن المنتجات...",
    productName: "اسم المنتج",
    category: "الفئة",
    price: "السعر",
    status: "الحالة",
    actions: "الإجراءات",
    noProductsFound: "لم يتم العثور على منتجات",
    tableView: "عرض الجدول",
    gridView: "عرض الشبكة",
    sections: "الأقسام",
    notifications: "الإخطارات",
    noNewNotifications: "لا توجد إخطارات جديدة",
    selectLanguage: "اختر اللغة",
    poweredByGoogleTranslate: "Powered by Google Translate",
    profileSettings: "إعدادات الملف الشخصي",
    changeLanguage: "تغيير اللغة",
    signOut: "تسجيل الخروج",
    image: "صورة",
    brand: "العلامة التجارية",
    noImage: "لا توجد صورة",
    show: "عرض",
    entries: "إدخالات",
    prev: "السابق",
    next: "التالي",
    login: "تسجيل الدخول",
    emailOrPhone: "البريد الإلكتروني أو الهاتف",
    enterEmailOrPhone: "أدخل البريد الإلكتروني أو الهاتف",
    password: "كلمة المرور",
    enterPassword: "أدخل كلمة المرور",
    signingIn: "جاري تسجيل الدخول...",
    signIn: "تسجيل الدخول",
    invalidCredentials: "بيانات اعتماد غير صحيحة",
  },
  hi: {
    dashboard: "डैशबोर्ड",
    products: "उत्पाद",
    categories: "श्रेणियां",
    orders: "आदेश",
    customers: "ग्राहक",
    users: "उपयोगकर्ता",
    settings: "सेटिंग्स",
    logout: "लॉगआउट",
    profile: "प्रोफ़ाइल",
    add: "जोड़ें",
    edit: "संपादित करें",
    delete: "हटाएं",
    save: "सहेजें",
    cancel: "रद्द करें",
    search: "खोज",
    filter: "फ़िल्टर",
    apply: "लागू करें",
    close: "बंद करें",
    loading: "लोड हो रहा है",
    error: "त्रुटि",
    success: "सफलता",
    addProduct: "उत्पाद जोड़ें",
    manageProductCatalog: "अपनी उत्पाद सूची प्रबंधित करें",
    searchProducts: "उत्पाद खोजें...",
    productName: "उत्पाद का नाम",
    category: "श्रेणी",
    price: "कीमत",
    status: "स्थिति",
    actions: "कार्य",
    noProductsFound: "कोई उत्पाद नहीं मिला",
    tableView: "तालिका दृश्य",
    gridView: "ग्रिड दृश्य",
    sections: "अनुभाग",
    notifications: "सूचनाएं",
    noNewNotifications: "कोई नई सूचना नहीं",
    selectLanguage: "भाषा चुनें",
    poweredByGoogleTranslate: "Powered by Google Translate",
    profileSettings: "प्रोफ़ाइल सेटिंग्स",
    changeLanguage: "भाषा बदलें",
    signOut: "साइन आउट",
    image: "छवि",
    brand: "ब्रांड",
    noImage: "कोई छवि नहीं",
    show: "दिखाएं",
    entries: "प्रविष्टियां",
    prev: "पिछला",
    next: "अगला",
    login: "लॉगिन",
    emailOrPhone: "ईमेल या फोन",
    enterEmailOrPhone: "ईमेल या फोन दर्ज करें",
    password: "पासवर्ड",
    enterPassword: "पासवर्ड दर्ज करें",
    signingIn: "लॉगिन हो रहा है...",
    signIn: "लॉगिन",
    invalidCredentials: "अमान्य क्रेडेंशियल",
  },
  ko: {
    dashboard: "대시보드",
    products: "제품",
    categories: "카테고리",
    orders: "주문",
    customers: "고객",
    users: "사용자",
    settings: "설정",
    logout: "로그아웃",
    profile: "프로필",
    add: "추가",
    edit: "편집",
    delete: "삭제",
    save: "저장",
    cancel: "취소",
    search: "검색",
    filter: "필터",
    apply: "적용",
    close: "닫기",
    loading: "로딩 중",
    error: "오류",
    success: "성공",
    addProduct: "제품 추가",
    manageProductCatalog: "제품 카탈로그 관리",
    searchProducts: "제품 검색...",
    productName: "제품명",
    category: "카테고리",
    price: "가격",
    status: "상태",
    actions: "작업",
    noProductsFound: "제품을 찾을 수 없습니다",
    tableView: "테이블 보기",
    gridView: "그리드 보기",
    sections: "섹션",
    notifications: "알림",
    noNewNotifications: "새 알림 없음",
    selectLanguage: "언어 선택",
    poweredByGoogleTranslate: "Powered by Google Translate",
    profileSettings: "프로필 설정",
    changeLanguage: "언어 변경",
    signOut: "로그아웃",
    image: "이미지",
    brand: "브랜드",
    noImage: "이미지 없음",
    show: "표시",
    entries: "항목",
    prev: "이전",
    next: "다음",
    login: "로그인",
    emailOrPhone: "이메일 또는 전화",
    enterEmailOrPhone: "이메일 또는 전화 입력",
    password: "비밀번호",
    enterPassword: "비밀번호 입력",
    signingIn: "로그인 중...",
    signIn: "로그인",
    invalidCredentials: "잘못된 자격 증명",
  },
};

export const SUPPORTED_LANGUAGES = {
  en: { name: "English", flag: "🇺🇸" },
  es: { name: "Spanish", flag: "🇪🇸" },
  fr: { name: "French", flag: "🇫🇷" },
  de: { name: "German", flag: "🇩🇪" },
  it: { name: "Italian", flag: "🇮🇹" },
  pt: { name: "Portuguese", flag: "🇵🇹" },
  ru: { name: "Russian", flag: "🇷🇺" },
  ja: { name: "Japanese", flag: "🇯🇵" },
  zh: { name: "Chinese", flag: "🇨🇳" },
  ar: { name: "Arabic", flag: "🇸🇦" },
  hi: { name: "Hindi", flag: "🇮🇳" },
  ko: { name: "Korean", flag: "🇰🇷" },
};

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState(() => {
    return localStorage.getItem("appLanguage") || "en";
  });

  const t = (key) => {
    return translations[currentLanguage]?.[key] || translations.en[key] || key;
  };

  const changeLanguage = (languageCode) => {
    if (SUPPORTED_LANGUAGES[languageCode]) {
      setCurrentLanguage(languageCode);
      localStorage.setItem("appLanguage", languageCode);
    }
  };

  const value = {
    currentLanguage,
    changeLanguage,
    t,
    supportedLanguages: SUPPORTED_LANGUAGES,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};
